/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.tilleggsstonader.libs.logs

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
